# Generated by Django 4.1.4 on 2022-12-26 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
